version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/rust:latest
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
    steps:
      - checkout
      - run:
          name: Nightly Build Desktop
          command: |
            sudo apt-get install libudev-dev
            sudo apt-get install libasound2-dev
            sudo apt-get install alsa-utils
            rustup toolchain install nightly-2019-12-20
            rustup default nightly-2019-12-20
            rustup run nightly-2019-12-20 rustc --version --verbose
            rustup run nightly-2019-12-20 cargo --version --verbose
            rustup run nightly-2019-12-20 cargo build
            rustup run nightly-2019-12-20 cargo build --release
      - run:
          name: Nightly Build Web
          command: |
            rustup toolchain install nightly-2019-12-20
            rustup default nightly-2019-12-20
            rustup run nightly-2019-12-20 rustc --version --verbose
            rustup run nightly-2019-12-20 cargo --version --verbose
            rustup run nightly-2019-12-20 cargo install cargo-web
            rustup run nightly-2019-12-20 cargo web deploy
            rustup run nightly-2019-12-20 cargo web deploy --release
