version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/rust:latest
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Nightly Build
          command: |
            sudo apt-get install libudev-dev
            sudo apt-get install libasound2-dev
            sudo apt-get install alsa-utils
            rustup install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
            rustup run nightly cargo build --release
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"